name: Deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./